/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Valquíria Anacleto
 */
public class TelaInicialView extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicialView
     */
    public TelaInicialView() {
       
        
        initComponents();
         this.setVisible(true);
       
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        lblPeriodo = new javax.swing.JLabel();
        jComboBoxPeriodo = new javax.swing.JComboBox<>();
        lblTemperaturaMedia = new javax.swing.JLabel();
        lblHumidadeMedia = new javax.swing.JLabel();
        lblPressaoMedia = new javax.swing.JLabel();
        lblNumRegistro = new javax.swing.JLabel();
        lblTemperaturaMediaResultado = new javax.swing.JLabel();
        lblHumidadeMediaResultado = new javax.swing.JLabel();
        lblPressaoMediaResultado = new javax.swing.JLabel();
        lblNumRegistroAtualizado = new javax.swing.JLabel();
        btnFecharMedia = new javax.swing.JButton();
        jInternalFrame4 = new javax.swing.JInternalFrame();
        lblPressao = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblTemperatura = new javax.swing.JLabel();
        lblHumidade = new javax.swing.JLabel();
        txtPressao = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtTemperatura = new javax.swing.JTextField();
        txtHumidade = new javax.swing.JTextField();
        btnIncluir = new javax.swing.JButton();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        lblDataAtl = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        lblTemperaturaAtl = new javax.swing.JLabel();
        lblHumidadeAtl = new javax.swing.JLabel();
        lblPressaoAtl = new javax.swing.JLabel();
        lblDataAtlResultado = new javax.swing.JLabel();
        lblTemperaturaAtlResultado = new javax.swing.JLabel();
        lblHumidadeAtlResultado = new javax.swing.JLabel();
        lblPressaoAtlResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jInternalFrame2.setResizable(true);
        jInternalFrame2.setTitle("Dados Médios");
        jInternalFrame2.setVisible(true);
        jInternalFrame2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPeriodo.setText("Período");
        jInternalFrame2.getContentPane().add(lblPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jComboBoxPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPeriodoActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jComboBoxPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 120, -1));

        lblTemperaturaMedia.setText("Temperatura:");
        jInternalFrame2.getContentPane().add(lblTemperaturaMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        lblHumidadeMedia.setText("Humidade:");
        jInternalFrame2.getContentPane().add(lblHumidadeMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblPressaoMedia.setText("Pressão:");
        jInternalFrame2.getContentPane().add(lblPressaoMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        lblNumRegistro.setText("Número de registros:");
        jInternalFrame2.getContentPane().add(lblNumRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        lblTemperaturaMediaResultado.setText("Temperatura:");
        jInternalFrame2.getContentPane().add(lblTemperaturaMediaResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        lblHumidadeMediaResultado.setText("Humidade:");
        jInternalFrame2.getContentPane().add(lblHumidadeMediaResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        lblPressaoMediaResultado.setText("Pressão:");
        jInternalFrame2.getContentPane().add(lblPressaoMediaResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        lblNumRegistroAtualizado.setText("Número de registros");
        jInternalFrame2.getContentPane().add(lblNumRegistroAtualizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        btnFecharMedia.setText("Fechar");
        jInternalFrame2.getContentPane().add(btnFecharMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jInternalFrame4.setResizable(true);
        jInternalFrame4.setTitle("Dados do tempo");
        jInternalFrame4.setVisible(true);
        jInternalFrame4.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPressao.setText("Pressão:");
        jInternalFrame4.getContentPane().add(lblPressao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblData.setText("Data:");
        jInternalFrame4.getContentPane().add(lblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblTemperatura.setText("Temperatura:");
        jInternalFrame4.getContentPane().add(lblTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lblHumidade.setText("Humidade:");
        jInternalFrame4.getContentPane().add(lblHumidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtPressao.setText(" ");
        jInternalFrame4.getContentPane().add(txtPressao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 120, -1));

        txtData.setText(" ");
        jInternalFrame4.getContentPane().add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 120, -1));

        txtTemperatura.setText(" ");
        jInternalFrame4.getContentPane().add(txtTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 120, -1));

        txtHumidade.setText(" ");
        jInternalFrame4.getContentPane().add(txtHumidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 120, -1));

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(btnIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 170, 70, -1));

        jInternalFrame3.setResizable(true);
        jInternalFrame3.setTitle("Ultima atualização do tempo");
        jInternalFrame3.setVisible(true);
        jInternalFrame3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDataAtl.setText("Data:");
        jInternalFrame3.getContentPane().add(lblDataAtl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnFechar.setText("Fechar");
        jInternalFrame3.getContentPane().add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        lblTemperaturaAtl.setText("Temperatura:");
        jInternalFrame3.getContentPane().add(lblTemperaturaAtl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lblHumidadeAtl.setText("Humidade:");
        jInternalFrame3.getContentPane().add(lblHumidadeAtl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        lblPressaoAtl.setText("Pressão:");
        jInternalFrame3.getContentPane().add(lblPressaoAtl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblDataAtlResultado.setText("Data:");
        jInternalFrame3.getContentPane().add(lblDataAtlResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        lblTemperaturaAtlResultado.setText("Temperatura:");
        jInternalFrame3.getContentPane().add(lblTemperaturaAtlResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        lblHumidadeAtlResultado.setText("Humidade:");
        jInternalFrame3.getContentPane().add(lblHumidadeAtlResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        lblPressaoAtlResultado.setText("Pressão:");
        jInternalFrame3.getContentPane().add(lblPressaoAtlResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jInternalFrame4, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jInternalFrame3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jInternalFrame3, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jInternalFrame1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPeriodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPeriodoActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIncluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnFecharMedia;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JComboBox<String> jComboBoxPeriodo;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDataAtl;
    private javax.swing.JLabel lblDataAtlResultado;
    private javax.swing.JLabel lblHumidade;
    private javax.swing.JLabel lblHumidadeAtl;
    private javax.swing.JLabel lblHumidadeAtlResultado;
    private javax.swing.JLabel lblHumidadeMedia;
    private javax.swing.JLabel lblHumidadeMediaResultado;
    private javax.swing.JLabel lblNumRegistro;
    private javax.swing.JLabel lblNumRegistroAtualizado;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblPressao;
    private javax.swing.JLabel lblPressaoAtl;
    private javax.swing.JLabel lblPressaoAtlResultado;
    private javax.swing.JLabel lblPressaoMedia;
    private javax.swing.JLabel lblPressaoMediaResultado;
    private javax.swing.JLabel lblTemperatura;
    private javax.swing.JLabel lblTemperaturaAtl;
    private javax.swing.JLabel lblTemperaturaAtlResultado;
    private javax.swing.JLabel lblTemperaturaMedia;
    private javax.swing.JLabel lblTemperaturaMediaResultado;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtHumidade;
    private javax.swing.JTextField txtPressao;
    private javax.swing.JTextField txtTemperatura;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtData() {
        return txtData;
    }

    public JTextField  getTxtTemperatura() {
         return txtTemperatura;
    }

    public JTextField  getTxtHumidade() {
         return txtHumidade;

    }

    public JTextField  getTxtPressao() {
         return txtPressao;
    }

    public JTextField  getDataAtual() {
                 return txtData;
    }

    public JTextField getTemperaturaAtual() {
          return txtTemperatura;
            

    }

    public JTextField getHumidadeAtual() {
        return txtHumidade;
    }

    public JTextField getPressaoAtual() {
   return txtPressao;
    }

    public JButton getBtnIncluir() {
        return btnIncluir;
    }
}
