/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;


/**
 *
 * @author Valquíria Anacleto
 */
public class TelaInicialView extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicialView
     */
    public TelaInicialView() {

        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        lblTemperaturaMedia = new javax.swing.JLabel();
        lblHumidadeMedia = new javax.swing.JLabel();
        lblPressaoMedia = new javax.swing.JLabel();
        lblNumRegistro = new javax.swing.JLabel();
        lblTemperaturaMediaResultado = new javax.swing.JLabel();
        lblHumidadeMediaResultado = new javax.swing.JLabel();
        lblPressaoMediaResultado = new javax.swing.JLabel();
        lblNumRegistroAtualizado = new javax.swing.JLabel();
        btnFecharMedia = new javax.swing.JButton();
        jInternalFrame4 = new javax.swing.JInternalFrame();
        lblPressao = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblTemperatura = new javax.swing.JLabel();
        lblHumidade = new javax.swing.JLabel();
        txtPressao = new javax.swing.JTextField();
        txtTemperatura = new javax.swing.JTextField();
        txtHumidade = new javax.swing.JTextField();
        btnIncluir = new javax.swing.JButton();
        txtData = new javax.swing.JFormattedTextField();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        lblDataAtl = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        lblTemperaturaAtl = new javax.swing.JLabel();
        lblHumidadeAtl = new javax.swing.JLabel();
        lblPressaoAtl = new javax.swing.JLabel();
        lblDataAtual = new javax.swing.JLabel();
        lblTemperaturaAtual = new javax.swing.JLabel();
        lblHumidadeAtual = new javax.swing.JLabel();
        lblPressaoAtual = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jInternalFrame5 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDadosTempo = new javax.swing.JTable();
        btnExcluirDadoTabela = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jInternalFrame2.setResizable(true);
        jInternalFrame2.setTitle("Dados Médios");
        jInternalFrame2.setVisible(true);
        jInternalFrame2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTemperaturaMedia.setText("Temperatura:");
        jInternalFrame2.getContentPane().add(lblTemperaturaMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        lblHumidadeMedia.setText("Humidade:");
        jInternalFrame2.getContentPane().add(lblHumidadeMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lblPressaoMedia.setText("Pressão:");
        jInternalFrame2.getContentPane().add(lblPressaoMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblNumRegistro.setText("Número de registros:");
        jInternalFrame2.getContentPane().add(lblNumRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        lblTemperaturaMediaResultado.setText("-----");
        jInternalFrame2.getContentPane().add(lblTemperaturaMediaResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        lblHumidadeMediaResultado.setText("-----");
        jInternalFrame2.getContentPane().add(lblHumidadeMediaResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        lblPressaoMediaResultado.setText("-----");
        jInternalFrame2.getContentPane().add(lblPressaoMediaResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        lblNumRegistroAtualizado.setText("-----");
        jInternalFrame2.getContentPane().add(lblNumRegistroAtualizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        btnFecharMedia.setText("Fechar");
        btnFecharMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharMediaActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(btnFecharMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jInternalFrame4.setResizable(true);
        jInternalFrame4.setTitle("Dados do tempo");
        jInternalFrame4.setVisible(true);
        jInternalFrame4.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPressao.setText("Pressão:");
        jInternalFrame4.getContentPane().add(lblPressao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblData.setText("Data:");
        jInternalFrame4.getContentPane().add(lblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblTemperatura.setText("Temperatura:");
        jInternalFrame4.getContentPane().add(lblTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lblHumidade.setText("Humidade:");
        jInternalFrame4.getContentPane().add(lblHumidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtPressao.setText(" ");
        jInternalFrame4.getContentPane().add(txtPressao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 120, -1));

        txtTemperatura.setText(" ");
        jInternalFrame4.getContentPane().add(txtTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 120, -1));

        txtHumidade.setText(" ");
        jInternalFrame4.getContentPane().add(txtHumidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 120, -1));

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(btnIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 170, 70, -1));

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 120, -1));

        jInternalFrame3.setResizable(true);
        jInternalFrame3.setTitle("Ultima atualização do tempo");
        jInternalFrame3.setVisible(true);
        jInternalFrame3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDataAtl.setText("Data:");
        jInternalFrame3.getContentPane().add(lblDataAtl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnFechar.setText("Fechar");
        jInternalFrame3.getContentPane().add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        lblTemperaturaAtl.setText("Temperatura:");
        jInternalFrame3.getContentPane().add(lblTemperaturaAtl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lblHumidadeAtl.setText("Humidade:");
        jInternalFrame3.getContentPane().add(lblHumidadeAtl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        lblPressaoAtl.setText("Pressão:");
        jInternalFrame3.getContentPane().add(lblPressaoAtl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblDataAtual.setText("-----");
        jInternalFrame3.getContentPane().add(lblDataAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        lblTemperaturaAtual.setText("-----");
        jInternalFrame3.getContentPane().add(lblTemperaturaAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        lblHumidadeAtual.setText("-----");
        jInternalFrame3.getContentPane().add(lblHumidadeAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        lblPressaoAtual.setText("-----");
        jInternalFrame3.getContentPane().add(lblPressaoAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jInternalFrame5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jInternalFrame5.setTitle("Tabela de Dados");
        jInternalFrame5.setVisible(true);

        jScrollPane1.setBorder(null);

        jTDadosTempo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Temperatura", "humidade", "Pressão"
            }
        ));
        jScrollPane1.setViewportView(jTDadosTempo);

        btnExcluirDadoTabela.setText("Excluir");

        javax.swing.GroupLayout jInternalFrame5Layout = new javax.swing.GroupLayout(jInternalFrame5.getContentPane());
        jInternalFrame5.getContentPane().setLayout(jInternalFrame5Layout);
        jInternalFrame5Layout.setHorizontalGroup(
            jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
            .addGroup(jInternalFrame5Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(btnExcluirDadoTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame5Layout.setVerticalGroup(
            jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnExcluirDadoTabela))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jInternalFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jInternalFrame5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jInternalFrame4, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInternalFrame4, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jInternalFrame5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jInternalFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 130, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void btnFecharMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharMediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFecharMediaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirDadoTabela;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnFecharMedia;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JInternalFrame jInternalFrame5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTDadosTempo;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDataAtl;
    private javax.swing.JLabel lblDataAtual;
    private javax.swing.JLabel lblHumidade;
    private javax.swing.JLabel lblHumidadeAtl;
    private javax.swing.JLabel lblHumidadeAtual;
    private javax.swing.JLabel lblHumidadeMedia;
    private javax.swing.JLabel lblHumidadeMediaResultado;
    private javax.swing.JLabel lblNumRegistro;
    private javax.swing.JLabel lblNumRegistroAtualizado;
    private javax.swing.JLabel lblPressao;
    private javax.swing.JLabel lblPressaoAtl;
    private javax.swing.JLabel lblPressaoAtual;
    private javax.swing.JLabel lblPressaoMedia;
    private javax.swing.JLabel lblPressaoMediaResultado;
    private javax.swing.JLabel lblTemperatura;
    private javax.swing.JLabel lblTemperaturaAtl;
    private javax.swing.JLabel lblTemperaturaAtual;
    private javax.swing.JLabel lblTemperaturaMedia;
    private javax.swing.JLabel lblTemperaturaMediaResultado;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtHumidade;
    private javax.swing.JTextField txtPressao;
    private javax.swing.JTextField txtTemperatura;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtData() {
        return txtData;
    }

    public JTextField getTxtTemperatura() {
        return txtTemperatura;
    }

    public JTextField getTxtHumidade() {
        return txtHumidade;

    }

    public JTextField getTxtPressao() {
        return txtPressao;
    }

    
    
    public void setDataAtual(String text) {
        this.lblDataAtual.setText(text);
    }

    public void setTemperaturaAtual(String text) {

      this.lblTemperaturaAtual.setText(text);

    }

    public void setHumidadeAtual(String text) {

        this.lblHumidadeAtual.setText(text);

    }

    public void setPressaoAtual(String text) {

       this.lblPressaoAtual.setText(text);

    }
    
   
    public JTable getDadosTabela() {
        return jTDadosTempo;
    }
    
    public void setMediaTemperatura(String text) {
        this.lblTemperaturaMediaResultado.setText(text);
    }
    
    public void setMediaHumidade(String text) {
        this.lblHumidadeMediaResultado.setText(text);
    }
    public void setMediaPressao(String text) {
        this.lblPressaoMediaResultado.setText(text);
    }
    
     public void setNumeroRegistro(String text) {
        this.lblNumRegistroAtualizado.setText(text);
    }
    
    
    

    public JButton getBtnIncluir() {
        return btnIncluir;
    }
    
    public JButton getBtnExcluirDados() {
        return btnExcluirDadoTabela;
    }
    
    
}
